project:
  type: website
  output-dir: docs

website:
  title: "fnaufel"
  site-url: https://fnaufel.github.io
  description: "Professor Associado, RCN, UFF"
  favicon: images/avatar.jpg
  image: images/icon.png
  repo-url: https://github.com/fnaufel/fnaufel.github.io
  repo-branch: master
  reader-mode: true
  comments:
    giscus:
      repo: fnaufel/fnaufel.github.io
      repo-id: MDEwOlJlcG9zaXRvcnkyMzQ3OTA1Njc=
      category: Announcements
      category-id: DIC_kwDODf6ep84CYfNQ
      mapping: pathname
      reactions-enabled: true
      input-position: top
      language: pt
  page-footer: 
    left: 
      - text: "LICENÇA CC-BY-NC-SA"
        href: licenca.qmd
    right:
      - text: Desenvolvido com Quarto
        href: https://quarto.org/
  search: 
    location: navbar
    type: textbox
  navbar:
    logo: images/icon.png
    background: dark
    foreground: light
    pinned: true
    collapse: true
    right:
      - href: index.qmd
        text: Blog
        aria-label: Blog
      - href: md.qmd
        text: MD
        aria-label: MD
      - href: probest.qmd
        text: ProbEst
        aria-label: Probabililidade e Estatística
      - href: ga.qmd
        text: GA
        aria-label: GA
      - href: pubs.qmd
        text: Publicações
        aria-label: Publicações
      - href: about.qmd
        text: Sobre
        aria-label: Sobre
      - icon: github
        href: https://github.com/fnaufel
        aria-label: GitHub
      - icon: youtube
        href: https://www.youtube.com/@serenitasfifty1185
        aria-label: YouTube
      - icon: rss
        href: index.xml        
        
format:
  html:
    theme: 
      light: journal 
      dark: slate
    css: styles.css
    lang: pt
    date-format: DD/MM/YYYY
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: ^(?:http:|https:)\/\/fnaufel\.github\.io
    email-obfuscation: javascript
    resources:
      - "site/index.html"
      - "publications/*"
