theme = "hugo-academic"
baseURL = "https://fnaufel.github.io/site"
title = "fnaufel"

publishDir = "public"

languageCode = ["pt", "en"]
defaultContentLanguage = "pt" 
defaultContentLanguageInSubdir = true


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "cache$"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    post = "/:year/:month/:day/:slug/"
