theme = "hugo-academic"
baseURL = "https://fnaufel.github.io/site"
title = "fnaufel"

publishDir = "public"

languageCode = "pt"
defaultContentLanguage = "pt" 
defaultContentLanguageInSubdir = true

[languages]

[languages.en]
languageCode = "en-us"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "cache$"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

