---
title: "Probabilidade e Estatística (RCN00037)"
listing:
  id: probest-listings
  contents: posts
  type: grid
  sort: "date desc"
  date-format: short
  categories: false
  include: 
    categories: "probest"
---

::: {.callout-important title="Postagens recentes"}

Ao longo do semestre, acompanhe as postagens [mais abaixo, nesta mesma página](#listing-probest-listings).

:::


## Livro eletrônico

A versão preliminar está em [https://fnaufel.github.io/probestr/](https://fnaufel.github.io/probestr/){target="_blank"}.


## Outras referências

* Ron Larson, Betsy Farber, *Estatística Aplicada*, 6ed, Pearson, 2016.
* Richard D. De Veaux, Paul F. Velleman, David E. Bock, *Stats: Data and Models*, 4ed, Pearson, 2016.
* [Livros sobre R e Ciência de Dados](/site/pt/2020/01/18/livros-online-sobre-r-e-tidyverse/).


## Vídeos

Siga o [canal do seu professor favorito](https://www.youtube.com/channel/UCg2GkejTo4r0taLHZspLEMQ). Lá você encontra a *playlist* de Probabilidade e Estatística:

<iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PL7SRLwLs7ocaV-Y1vrVU3W7mZnnS0qkWV" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


## Software

Todos os arquivos usados nos vídeos estão no [repositório do curso no GitHub](https://github.com/fnaufel/CursoProbEst#readme){target="_blank"}. Lá, você encontra instruções para ter acesso a eles, *online* ou no seu computador.


## Cronograma e outras informações

No [Moodle](https://ead.cead.uff.br/). Entre em contato se você ainda não tem acesso.


## Postagens recentes sobre ProbEst

::: {#probest-listings}
:::

