---
title: Geometria Analítica e Cálculo Vetorial

reading_time: false  # Show estimated reading time?
share: true  # Show social sharing links?
profile: true  # Show author profile?
comments: false  # Show comments?

# Optional header image (relative to `assets/media/` folder).
header:
  caption: ""
  image: ""
---

## Descrição

Informações sobre a disciplina RCN00023 dos cursos de Ciência da Computação e de Engenharia de Produção do PURO da Universidade Federal Fluminense. 


## Livros

Vamos usar o material do [CEDERJ](https://canal.cecierj.edu.br/){target="_blank"}. 

Os PDFs estão em 

* [https://canal.cecierj.edu.br/recurso/4690](https://canal.cecierj.edu.br/recurso/4690){target="_blank"} (volume 1)

* [https://canal.cecierj.edu.br/recurso/4549](https://canal.cecierj.edu.br/recurso/4549){target="_blank"} (volume 2)

Além disso, você encontra mais material no [livro interativo *GA não é cringe*](https://www.geogebra.org/m/w98zzmt8){target="_blank"}.


## Vídeos

Siga o canal do seu professor favorito, que está em [https://www.youtube.com/channel/UCg2GkejTo4r0taLHZspLEMQ](https://www.youtube.com/channel/UCg2GkejTo4r0taLHZspLEMQ){target="_blank"}.

Lá você encontra a *playlist* de GA:

<iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PL7SRLwLs7ocaQDC-qPjBWCnG46jYofs67" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Consulte o calendário do curso e assista aos vídeos sobre o assunto da semana.

Não esqueça de indicar o canal para seus coleguinhas.


## Software

Aprenda a usar o [Geogebra](https://www.geogebra.org/){target="_blank"}, ou *online* ou instalado no seu celular, *tablet* ou computador.

Existem muitos vídeos com [tutoriais em português sobre o Geogebra](https://www.youtube.com/results?search_query=geogebra+portugu%C3%AAs){target="_blank"}.


## Cronograma e outras informações

No Moodle. [Entre em contato](/site/pt/contact/) se você ainda não tem acesso.


## Edições passadas do curso

### 2021.2

#### Lista 1: construindo uma casa no $\mathbb{R}^2$

* [Enunciado.](/site/static/GA/2022.1/casa2d.html){target="_blank"}

* [Solução.](/site/static/GA/2022.1/casa2d-gabarito.html){target="_blank"}
 
#### Lista 2: construindo um emoji com cônicas

* [Enunciado.](/site/static/GA/2022.1/emoji.html){target="_blank"}

* [Solução.](/site/static/GA/2022.1/emoji-gab.html){target="_blank"}


### 2021.1

Listas de exercícios que serviram como avaliação no semestre 2021.1, o terceiro a ser oferecido remotamente por causa da pandemia.

#### Lista 1: vetores, projeção ortogonal, cônicas

* [Enunciado.](/site/static/GA/2021.1/lista1.html){target="_blank"}

* [Solução.](https://www.geogebra.org/m/w98zzmt8#material/uyrwturt){target="_blank"}

#### Lista 2: construindo uma casa no $\mathbb{R}^3$

* [Enunciado.](/site/static/GA/2021.1/lista2.html){target="_blank"}

* [Solução.](https://www.geogebra.org/m/knmkcbe4){target="_blank"}


### 2020.2

Listas de exercícios que serviram como avaliação no semestre 2020.2, o segundo a ser oferecido remotamente por causa da pandemia.

#### Lista 1: cônicas

* [Enunciado.](/site/static/GA/2020.2/2020.2-lista1.html){target="_blank"}


#### Lista 2: esferas e retas no espaço

* [Enunciado.](/site/static/GA/2020.2/lista2.html){target="_blank"}

* [Solução.](/site/static/GA/2020.2/lista2-gab.html){target="_blank"}


### 2020.1

Listas de exercícios que serviram como avaliação no semestre 2020.1, o primeiro a ser oferecido remotamente por causa da pandemia.

#### Lista 1: retas, vetores, projeção ortogonal

* [Enunciado.](/site/static/GA/2020.1/lista1.html){target="_blank"}

* [Solução.](/site/static/GA/2020.1/lista1-gabarito.html){target="_blank"}

#### Lista 2: cônicas

* [Enunciado.](/site/static/GA/2020.1/lista2.html){target="_blank"}


## Quando provas ainda eram no papel

[Arquivo .zip](https://drive.google.com/file/d/1HsSzo3eflh7p2TbpBphG9m6WCNW3BA2h/view?usp=sharing){target="_blank"} com provas e gabaritos em arquivos pdf.


