---
title: Geometria Analítica e Cálculo Vetorial (RCN00023)
author: fnaufel
date: '2021-09-05'
slug: []
categories:
  - ga
tags:
  - universidade
  - cursos
subtitle: ''
summary: ''
authors: []
lastmod: '2021-09-05T13:51:17-03:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

## Descrição

Informações sobre a disciplina RCN00023 dos cursos de Ciência da Computação e de Engenharia de Produção do PURO da Universidade Federal Fluminense. 


## Livros

Vamos usar o material do [CEDERJ](https://canal.cecierj.edu.br/){target="_blank"}. 

Os PDFs estão em 

* [https://canal.cecierj.edu.br/recurso/4690](https://canal.cecierj.edu.br/recurso/4690){target="_blank"} (volume 1)

* [https://canal.cecierj.edu.br/recurso/4549](https://canal.cecierj.edu.br/recurso/4549){target="_blank"} (volume 2)

Além disso, você encontra mais material no [livro interativo *GA não é cringe*](https://www.geogebra.org/m/w98zzmt8){target="_blank"}.


## Vídeos

Siga o canal do seu professor favorito, que está em [https://www.youtube.com/channel/UCg2GkejTo4r0taLHZspLEMQ](https://www.youtube.com/channel/UCg2GkejTo4r0taLHZspLEMQ){target="_blank"}.

Lá você encontra a *playlist* de GA:

<iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PL7SRLwLs7ocaQDC-qPjBWCnG46jYofs67" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Consulte o calendário do curso e assista aos vídeos sobre o assunto da semana. Eles substituem as aulas presenciais.

São vídeos feitos com carinho e atenção pelo seu professor. Você pode assistir quando quiser, quantas vezes quiser, dar pausa quando quiser --- diferente da aula presencial.

Não esqueça de indicar o canal para seus coleguinhas.


## Software

Aprenda a usar o [Geogebra](https://www.geogebra.org/){target="_blank"}, ou *online* ou instalado no seu celular, *tablet* ou computador.

Existem muitos vídeos com [tutoriais em português sobre o Geogebra](https://www.youtube.com/results?search_query=geogebra+portugu%C3%AAs){target="_blank"}.


## Provas passadas

[Arquivo .zip](https://drive.google.com/file/d/1HsSzo3eflh7p2TbpBphG9m6WCNW3BA2h/view?usp=sharing){target="_blank"} com provas e gabaritos em arquivos pdf.

Veja também as [páginas sobre edições desta disciplina](/site/pt/ga/){target="_blank"} em semestres específicos.


## Cronograma e outras informações

No Moodle. [Entre em contato](/site/pt/contact/) se você ainda não tem acesso.

