---
title: Probabilidade e Estatística

reading_time: false  # Show estimated reading time?
share: true  # Show social sharing links?
profile: true  # Show author profile?
comments: false  # Show comments?

# Optional header image (relative to `assets/media/` folder).
header:
  caption: ""
  image: ""
---

## Descrição

Informações sobre a disciplina RCN00037 do curso de Ciência da Computação do PURO da Universidade Federal Fluminense. 


## Livro eletrônico

Estou desenvolvendo um livro eletrônico com o conteúdo do curso.

A versão preliminar está em [https://fnaufel.github.io/probestr/](https://fnaufel.github.io/probestr/){target="_blank"}.

Você deve usar o livro eletrônico junto com a *playlist* de vídeos e com o repositório do GitHub. Mais informações abaixo.


## Outras referências

Minhas recomendações são

* Ron Larson, Betsy Farber, *Estatística Aplicada*, 6ed, Pearson, 2016.

* Richard D. De Veaux, Paul F. Velleman, David E. Bock, *Stats: Data and Models*, 4ed, Pearson, 2016.

* [Livros sobre R e Ciência de Dados](/site/pt/2020/01/18/livros-online-sobre-r-e-tidyverse/).


## Vídeos

Siga o canal do seu professor favorito, que está em [https://www.youtube.com/channel/UCg2GkejTo4r0taLHZspLEMQ](https://www.youtube.com/channel/UCg2GkejTo4r0taLHZspLEMQ){target="_blank"}.

Lá você encontra a *playlist* de Probabilidade e Estatística:

<iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PL7SRLwLs7ocaV-Y1vrVU3W7mZnnS0qkWV" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Consulte o calendário do curso e assista aos vídeos sobre o assunto da semana. Eles substituem as aulas presenciais.

Não esqueça de indicar o canal para seus coleguinhas.


## Software

Todos os arquivos usados nos vídeos estão no [repositório do curso no GitHub](https://github.com/fnaufel/CursoProbEst#readme){target="_blank"}.

Lá, você encontra instruções para ter acesso a eles, *online* ou no seu computador.


## Cronograma e outras informações

No Moodle. [Entre em contato](/site/pt/contact/) se você ainda não tem acesso.


## Material de semestres anteriores

### 2022.1

#### Lista 1: cidades brasileiras

* [Enunciado.](https://fnaufel.github.io/lista1-cidades-br/){target="_blank"}

* [Solução parcial.](/site/static/Probest/2022.1/cidades-gab.html){target="_blank"}

#### Lista 2: pessoas e medidas

* [Enunciado.](https://fnaufel.github.io/site/static/Probest/2022.1/ic-ih.html){target="_blank"}


### 2021.2

#### Lista 1: olimpíadas

* [Enunciado.](https://github.com/fnaufel/Olimpiadas/blob/master/README.md){target="_blank"}

* [Solução.](https://fnaufel.github.io/site/static/Probest/2021.2/olimpiadas-solucoes.html){target="_blank"}

#### Lista 2: intervalos de confiança e testes de hipóteses

* [Enunciado.](https://fnaufel.github.io/site/static/Probest/2021.2/ic-th.html){target="_blank"}

* [Solução.](https://fnaufel.github.io/site/static/Probest/2021.2/ic-th-solucoes.html){target="_blank"}


### 2021.1

Listas de exercícios que serviram como avaliação no semestre 2021.1, o terceiro a ser oferecido remotamente por causa da pandemia.

#### Lista 2: visualização e probabilidades

* [Enunciado.](/site/static/Probest/2021.1/lista2.html){target="_blank"}

* [Solução.](/site/static/Probest/2021.1/lista2-gab.html){target="_blank"}


### 2020.1

Listas de exercícios que serviram como avaliação no semestre 2020.1, o primeiro a ser oferecido remotamente por causa da pandemia.

#### Lista 1: visualização, medidas, probabilidades

* [Enunciado.](/site/static/Probest/2020.1/lista1.html){target="_blank"}

* [Solução.](/site/static/Probest/2020.1/lista1-gab.html){target="_blank"}


#### Lista 2: normal, Poisson, probabilidades

* [Enunciado.](/site/static/Probest/2020.1/lista2.html){target="_blank"}

* [Solução.](/site/static/Probest/2020.1/lista2-respostas.html){target="_blank"}

