---
title: Probabilidade e Estatística (RCN00037)
author: fnaufel
date: '2021-09-16'
slug: []
categories:
  - probest
tags:
  - cursos
  - r
  - universidade
subtitle: ''
summary: ''
authors: []
lastmod: '2021-09-16T11:43:23-03:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

## Descrição

Informações sobre a disciplina RCN00037 do curso de Ciência da Computação do PURO da Universidade Federal Fluminense. 


## Livros

Não vamos seguir nenhum livro em especial.

Minhas recomendações são

* Ron Larson, Betsy Farber, *Estatística Aplicada*, 6ed, Pearson, 2016.

* Richard D. De Veaux, Paul F. Velleman, David E. Bock, *Stats: Data and Models*, 4ed, Pearson, 2016.

* [Livros sobre R e Ciência de Dados](/site/pt/2020/01/18/livros-online-sobre-r-e-tidyverse/).


## Vídeos

Siga o canal do seu professor favorito, que está em [https://www.youtube.com/channel/UCg2GkejTo4r0taLHZspLEMQ](https://www.youtube.com/channel/UCg2GkejTo4r0taLHZspLEMQ){target="_blank"}.

Lá você encontra a *playlist* de Probabilidade e Estatística:

<iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PL7SRLwLs7ocaV-Y1vrVU3W7mZnnS0qkWV" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Consulte o calendário do curso e assista aos vídeos sobre o assunto da semana. Eles substituem as aulas presenciais.

São vídeos feitos com carinho e atenção pelo seu professor. Você pode assistir quando quiser, quantas vezes quiser, dar pausa quando quiser --- diferente da aula presencial.

Não esqueça de indicar o canal para seus coleguinhas.


## Software

Todos os arquivos usados nos vídeos estão no [repositório do curso no GitHub](https://github.com/fnaufel/CursoProbEst#readme){target="_blank"}.

Lá, você encontra instruções para ter acesso a eles, *online* ou no seu computador.

Estou desenvolvendo um livro eletrônico interativo baseado nesse material. Postarei mais informações aqui ao longo do tempo.


## Material de semestres anteriores

Veja as [páginas sobre edições desta disciplina](/site/pt/probest/){target="_blank"} em semestres específicos.


## Cronograma e outras informações

No Moodle. [Entre em contato](/site/pt/contact/) se você ainda não tem acesso.

